title: "Sony Shop"
url: "https://monsoonmalabar.com/sonyshop"
email: "justinechacko1@gmail.com"
markdown: kramdown
mobile: "919633464330"
country: "India"
currency_code: "USD"
paypal_email: "mazhavilmallus@gmail.com"
razorpay_key: ""
location: "12.0418836,75.4017864"
category: "Kirana Store, FMCG & Grocery"
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
permalink: /products/:title/
paginate: 10
permalink: /:categories/:title/
paginate_path: 'page/:num/'
favicon: "https://i.imgur.com/ncrwl8V.png"
paypal: 
fb_appid: "494525305893363"
analytics: 
adsense: 